
#line 3 "lex.linguist_yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define linguist_yy_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer linguist_yy_create_buffer
#endif

#ifdef yy_delete_buffer
#define linguist_yy_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer linguist_yy_delete_buffer
#endif

#ifdef yy_scan_buffer
#define linguist_yy_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer linguist_yy_scan_buffer
#endif

#ifdef yy_scan_string
#define linguist_yy_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string linguist_yy_scan_string
#endif

#ifdef yy_scan_bytes
#define linguist_yy_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes linguist_yy_scan_bytes
#endif

#ifdef yy_init_buffer
#define linguist_yy_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer linguist_yy_init_buffer
#endif

#ifdef yy_flush_buffer
#define linguist_yy_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer linguist_yy_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define linguist_yy_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state linguist_yy_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define linguist_yy_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer linguist_yy_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define linguist_yypush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state linguist_yypush_buffer_state
#endif

#ifdef yypop_buffer_state
#define linguist_yypop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state linguist_yypop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define linguist_yyensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack linguist_yyensure_buffer_stack
#endif

#ifdef yylex
#define linguist_yylex_ALREADY_DEFINED
#else
#define yylex linguist_yylex
#endif

#ifdef yyrestart
#define linguist_yyrestart_ALREADY_DEFINED
#else
#define yyrestart linguist_yyrestart
#endif

#ifdef yylex_init
#define linguist_yylex_init_ALREADY_DEFINED
#else
#define yylex_init linguist_yylex_init
#endif

#ifdef yylex_init_extra
#define linguist_yylex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra linguist_yylex_init_extra
#endif

#ifdef yylex_destroy
#define linguist_yylex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy linguist_yylex_destroy
#endif

#ifdef yyget_debug
#define linguist_yyget_debug_ALREADY_DEFINED
#else
#define yyget_debug linguist_yyget_debug
#endif

#ifdef yyset_debug
#define linguist_yyset_debug_ALREADY_DEFINED
#else
#define yyset_debug linguist_yyset_debug
#endif

#ifdef yyget_extra
#define linguist_yyget_extra_ALREADY_DEFINED
#else
#define yyget_extra linguist_yyget_extra
#endif

#ifdef yyset_extra
#define linguist_yyset_extra_ALREADY_DEFINED
#else
#define yyset_extra linguist_yyset_extra
#endif

#ifdef yyget_in
#define linguist_yyget_in_ALREADY_DEFINED
#else
#define yyget_in linguist_yyget_in
#endif

#ifdef yyset_in
#define linguist_yyset_in_ALREADY_DEFINED
#else
#define yyset_in linguist_yyset_in
#endif

#ifdef yyget_out
#define linguist_yyget_out_ALREADY_DEFINED
#else
#define yyget_out linguist_yyget_out
#endif

#ifdef yyset_out
#define linguist_yyset_out_ALREADY_DEFINED
#else
#define yyset_out linguist_yyset_out
#endif

#ifdef yyget_leng
#define linguist_yyget_leng_ALREADY_DEFINED
#else
#define yyget_leng linguist_yyget_leng
#endif

#ifdef yyget_text
#define linguist_yyget_text_ALREADY_DEFINED
#else
#define yyget_text linguist_yyget_text
#endif

#ifdef yyget_lineno
#define linguist_yyget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno linguist_yyget_lineno
#endif

#ifdef yyset_lineno
#define linguist_yyset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno linguist_yyset_lineno
#endif

#ifdef yyget_column
#define linguist_yyget_column_ALREADY_DEFINED
#else
#define yyget_column linguist_yyget_column
#endif

#ifdef yyset_column
#define linguist_yyset_column_ALREADY_DEFINED
#else
#define yyset_column linguist_yyset_column
#endif

#ifdef yywrap
#define linguist_yywrap_ALREADY_DEFINED
#else
#define yywrap linguist_yywrap
#endif

#ifdef yyalloc
#define linguist_yyalloc_ALREADY_DEFINED
#else
#define yyalloc linguist_yyalloc
#endif

#ifdef yyrealloc
#define linguist_yyrealloc_ALREADY_DEFINED
#else
#define yyrealloc linguist_yyrealloc
#endif

#ifdef yyfree
#define linguist_yyfree_ALREADY_DEFINED
#else
#define yyfree linguist_yyfree
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyg->yytext_ptr -= yyg->yy_more_len; \
	yyleng = (int) (yy_cp - yyg->yytext_ptr); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 52
#define YY_END_OF_BUFFER 53
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[289] =
    {   0,
       53,   51,   52,   49,   51,   52,16429,   31,   51,   52,
       49,   51,   52,16429,   49,   51,   52,16429,   32,   51,
       52,   43,   51,   52,   43,   51,   52,   49,   51,   52,
    16429,   50,   51,   52,   39,   40,   41,   51,   52,   39,
       40,   41,   51,   52,   50,   51,   52,   41,   51,   52,
       41,   51,   52,   43,   51,   52,   41,   49,   51,   52,
    16429,   43,   51,   52,   51,   52,   31,   51,   52,   49,
       51,   52,16429,   49,   51,   52,16429,   32,   51,   52,
       49,   51,   52,16429,   49,   51,   52,16429,   50,   51,
       52,   49,   51,   52,16429,   52,   22,   52,   22,   52,

       22,   52,   22,   52,   22,   52,   22,   52,   22,   52,
       22,   52,   49,   52,16429,   50,   52,   44,   49,16429,
       30,   34,   41,   44,   41,   44,   41,   49,16429,   33,
       35,   44,   35,   44,   30,   42,   18,   46,   15,   40,
       38,   39,   40,   41,   39,   40,   41,   41,   41,   40,
       41,   41,   40,   41,   40,   41,   41,   37,   41,   17,
        8,    8,    3,   44,    3,   44,   49,16429,   49,16429,
        7,   44,    7,   44,   49,16429,   49,16429,   44,   49,
    16429,   41,   44,    9,   44,    9,   44,   49,16429,   23,
       25,   26, 8237,   19,   34,   41,   33,   35,   35,   20,

       14,   13,   48,   40,   40,   40,   40,   41,   36,   40,
       41,    3,    3,    7,    7,    9,    9,    8,    3,   44,
        2,   44,    2,   44,    2,   49,16429,    2,   44,    7,
       11,    6,   44,    6,   44,   10,   44,   41,    5,   46,
        5,   46,    9,   24,   27,   28,   29,   12,   40,   40,
       40,   41,   40,   36,   40,   41,   36,   40,   41,   36,
       40,   41,   16,    6,    6,    5,    5,    2,    2,    2,
        2,   11,   11,    6,   10,   10,   10,   21,    5,    4,
        4,   47,   40,   40,   40,    2,    4,    1
    } ;

static const flex_int16_t yy_accept[223] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    8,   11,   15,   19,   22,   25,   28,
       32,   35,   40,   45,   48,   51,   54,   57,   62,   65,
       67,   70,   74,   78,   81,   85,   89,   92,   96,   97,
       99,  101,  103,  105,  107,  109,  111,  113,  116,  118,
      119,  121,  121,  121,  122,  125,  127,  130,  133,  135,
      136,  137,  138,  139,  140,  140,  140,  141,  145,  148,
      149,  150,  152,  153,  155,  157,  158,  160,  160,  161,
      161,  161,  161,  161,  161,  161,  161,  162,  163,  165,

      167,  169,  171,  173,  175,  177,  177,  177,  179,  180,
      182,  184,  184,  186,  188,  190,  191,  191,  192,  193,
      193,  193,  193,  194,  194,  195,  197,  199,  200,  201,
      202,  203,  204,  204,  204,  205,  206,  207,  209,  212,
      212,  213,  214,  215,  216,  216,  216,  217,  218,  219,
      220,  221,  222,  223,  225,  228,  230,  231,  232,  234,
      236,  236,  236,  238,  239,  241,  243,  243,  243,  244,
      245,  246,  247,  248,  248,  249,  249,  250,  251,  253,
      254,  257,  260,  263,  264,  265,  266,  267,  268,  268,
      268,  269,  269,  270,  271,  271,  272,  273,  274,  275,

      276,  277,  278,  279,  280,  281,  282,  283,  284,  285,
      286,  286,  287,  288,  288,  288,  288,  288,  288,  289,
      289,  289
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   10,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   10,   22,   23,
       24,   25,   10,   26,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   30,
       30,   30,   30,   30,   32,   30,   30,   33,   30,   30,
       34,   35,   36,   10,   37,   10,   27,   27,   27,   27,

       38,   29,   39,   40,   41,   30,   30,   31,   30,   42,
       30,   30,   30,   30,   30,   30,   32,   43,   30,   33,
       30,   30,   44,   10,   45,   10,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[46] =
    {   0,
        1,    2,    3,    2,    4,    1,    4,    4,    4,    4,
        1,    1,    1,    1,    4,    4,    4,    5,    5,    5,
        5,    4,    1,    4,    4,    4,    5,    5,    5,    5,
        5,    5,    5,    1,    4,    1,    6,    5,    5,    5,
        5,    5,    5,    1,    1
    } ;

static const flex_int16_t yy_base[239] =
    {   0,
        0,   44,    0,    0,  538,  537,  534,  533,  531,  530,
      531,  530,  536,  533,  527,  526,  519,  518,   62,    0,
      534,  780,   95,  527,  132,  159,  521,   43,  780,   44,
       75,  186,   62,   78,  211,  236,  495,   54,   78,  275,
      121,  178,  295,  257,  269,  331,  108,  266,  780,  780,
      512,  513,  483,  514,  520,  514,  502,  286,  244,  780,
      319,  504,  511,  503,   87,    0,   95,  354,  174,  494,
      780,  780,  780,   44,  311,  322,  376,  462,  189,    0,
       75,   23,    0,  181,  455,  396,    0,  469,  780,    0,
      125,  230,  334,  462,  451,  304,  780,    0,  780,    0,

      433,  350,  780,    0,    0,  312,  453,  352,  342,  359,
      417,  366,  780,    0,  397,  780,  417,  780,  780,  433,
      421,  415,  780,  387,  780,  226,    0,    0,  780,  780,
      384,  780,  383,  205,  265,  367,  391,  356,  460,  370,
      780,    0,  780,    0,  232,  423,  780,    0,    0,    0,
      502,  539,  358,  301,  356,  371,    0,  361,  780,    0,
      386,  343,  298,  280,  780,    0,  283,  426,    0,  780,
      780,  780,  780,  264,  780,  255,  235,  426,    0,  561,
        0,  326,    0,  780,  780,    0,  780,    0,  464,  429,
      246,  193,  310,  469,  166,  470,   65,  780,    0,   56,

       44,  780,  780,    0,  780,    0,  780,  780,  363,    0,
      349,  510,    0,  288,  598,  492,  434,  446,  640,  513,
      780,  683,  689,  695,  701,  706,  712,  718,  724,  729,
      731,  737,  743,  749,  755,  761,  767,  773
    } ;

static const flex_int16_t yy_def[239] =
    {   0,
      221,    1,  222,  222,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  222,   19,
      221,  221,  224,  221,  221,   25,  221,  221,  221,   25,
      225,  221,   32,  225,  221,   35,  221,   25,  221,  221,
      221,   25,  224,  221,   43,   25,  225,   43,  221,  221,
      221,  221,  221,  221,  221,  221,  221,   43,  225,  221,
       43,  221,  221,  221,   36,   36,   25,  221,   68,  221,
      221,  221,  221,  221,  225,  225,  221,   32,   32,   35,
       35,   35,   36,   36,   36,   36,   36,  221,  221,   40,
      221,  221,  221,  221,  221,  221,  221,  226,  221,  227,

       25,   43,  221,  228,   43,  221,  221,   43,  221,   43,
       36,  225,  221,  229,   43,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,   36,   68,   69,  221,  221,
      221,  221,  221,  221,  221,  221,  221,   36,  221,  221,
      221,  227,  221,  228,  221,  221,  221,  229,  226,  227,
      230,  230,  231,  152,  101,  152,  228,  232,  221,  233,
      221,  221,  234,   36,  221,  235,  221,  225,  229,  221,
      221,  221,  221,  221,  221,  221,  221,  221,   36,  221,
      139,  139,  139,  221,  221,  233,  221,  235,  221,  152,
      152,  231,  152,  152,  231,  152,  232,  221,  233,  234,

      234,  221,  221,  235,  221,  236,  221,  221,  180,  180,
      231,  152,  236,  231,  237,  231,  237,  238,  237,  238,
        0,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221
    } ;

static const flex_int16_t yy_nxt[826] =
    {   0,
       22,   22,   22,   22,   23,   24,   25,   26,   23,   23,
       27,   28,   29,   23,   23,   23,   30,   31,   32,   33,
       33,   23,   34,   23,   23,   30,   35,   35,   35,   36,
       36,   36,   36,   37,   23,   29,   38,   35,   36,   36,
       36,   36,   36,   39,   29,   40,  221,   40,  130,   41,
       42,   82,   43,   84,   44,   71,   72,  131,  202,   45,
       46,   47,   66,   66,   66,   48,   58,  221,   58,   58,
       58,   58,   66,   66,   66,   58,   58,   58,   58,   59,
       79,   79,   88,   58,   59,   58,   58,   58,   74,  137,
      137,  221,   75,   89,   83,   75,   58,   76,   58,   61,

       76,   61,   61,   61,   61,  126,  126,  126,   61,   61,
       61,   61,   62,   66,   66,   66,   61,   63,   61,   61,
       61,   74,   71,   97,   98,  112,   64,   97,   98,   61,
       76,   61,   60,   60,   60,   60,   61,   60,   61,   61,
       61,   61,   60,   60,   60,   61,   61,   61,   61,   62,
       65,   65,   65,   61,   63,   61,   61,   61,   66,   66,
       66,   66,   66,   66,   66,   60,   61,   60,   67,   66,
       66,   66,   66,   66,   66,   60,   60,   68,   68,   68,
       99,  100,  101,  195,  102,   69,   69,   69,   60,   60,
       60,   60,  128,  128,  128,   61,   69,   60,   60,   60,

       60,   60,   77,  211,   78,   78,   79,   79,   79,   84,
      195,   84,   80,   81,   82,   83,   84,   85,   86,  137,
      137,   83,   83,   81,   83,   87,   83,   83,   83,   80,
       80,   80,  141,  142,  185,  186,   92,   80,   80,   80,
       83,   83,   83,   83,  126,  126,  126,   83,   80,   83,
       87,   83,   83,   83,   83,   83,   83,  221,  106,  221,
      106,   75,   83,   83,   83,  208,   76,   70,  113,  114,
      207,   60,   60,   83,   61,   83,   90,   61,   90,  123,
       91,   92,  203,   93,  108,  205,  206,  115,   60,   60,
       94,  107,   95,  135,   61,  135,   96,  103,  104,   61,

      202,   61,   61,  105,   61,  195,  147,  148,   61,   61,
       61,   61,   62,  106,  221,  106,   61,   63,   61,   61,
       61,   60,   60,  221,  132,   96,  133,   61,   75,   61,
      216,   61,  109,   76,  109,  221,  143,  144,  193,   75,
      137,  137,   93,  161,   76,  161,  107,  193,  200,   66,
       66,   66,   99,  100,  159,  160,  102,   60,   61,   60,
       61,   60,   60,  198,  163,  110,  195,   61,  165,  166,
      167,  111,  127,  127,  127,  195,  162,  137,  137,  132,
      128,  128,  128,  168,  221,  184,  179,  161,   76,  161,
      214,  128,   77,  154,   77,   77,   77,  177,  176,  113,

      114,  175,  174,  134,  135,   61,  135,  136,  193,  178,
      178,  178,  196,  134,  139,  139,  139,  173,  115,  135,
      162,  135,  139,  139,  139,  187,  188,  167,  165,  166,
      190,  172,  190,  139,  151,  221,  151,  221,  171,  132,
      189,  170,  221,  168,  178,  178,  178,  215,   76,  215,
      152,  153,  153,  153,  135,  164,  135,  218,  158,  154,
      154,  154,  154,  154,  154,  154,  187,  188,  146,  155,
      156,  154,  154,  154,  154,  154,  180,  145,  181,  181,
      181,  189,  221,  221,  140,  138,  181,  182,  183,   83,
       84,   85,   83,  215,   83,  215,   83,  182,   83,   83,

       83,   83,   83,  190,  129,  190,  193,  193,  125,  195,
      196,  215,  212,  215,  215,  124,  215,  123,  122,  191,
      192,  192,  192,  221,  121,  120,  119,  118,  117,  116,
       71,   70,   64,  221,   57,   57,   56,   56,   55,  194,
      221,   55,  221,   54,   54,   53,   53,  193,   52,   52,
       51,   51,  123,  221,  221,  221,  191,  192,  192,  192,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  194,  180,  221,  180,
      180,  180,  221,  221,  221,  221,  221,  180,  209,  210,
      221,  135,  136,  221,  221,  221,  221,  221,  209,  215,

      221,  215,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  218,  221,  221,  219,  219,  219,  219,  219,  219,
      219,  221,  221,  221,  219,  219,  219,  219,  219,  219,
      219,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  218,  221,  221,  219,  219,  219,  219,
      219,  219,  219,  221,  221,  221,  219,  219,  219,  219,
      219,  219,  219,   49,   49,   49,   49,   49,   49,   50,
       50,   50,   50,   50,   50,   60,   60,   60,   60,   60,

       60,   73,   73,   73,  221,   73,  149,  149,  221,  149,
      149,  149,  150,  150,  221,  150,  150,  150,  157,  157,
      221,  157,  157,  157,  169,  169,  221,  169,  169,  169,
      193,  221,  221,  193,  193,  192,  192,  197,  197,  197,
      197,  197,  197,  199,  199,  221,  199,  199,  199,  201,
      201,  201,  201,  201,  201,  204,  204,  221,  204,  204,
      204,  213,  213,  221,  213,  213,  213,  217,  217,  217,
      217,  217,  217,  220,  220,  220,  220,  220,  220,   21,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,

      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221
    } ;

static const flex_int16_t yy_chk[826] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,  201,    2,   74,    2,
        2,   82,    2,   82,    2,   28,   28,   74,  200,    2,
        2,    2,   30,   30,   30,    2,   19,  197,   19,   19,
       19,   19,   38,   38,   38,   19,   19,   19,   19,   19,
       33,   33,   34,   19,   19,   19,   19,   19,   31,   81,
       81,   34,   31,   39,   33,   34,   19,   31,   19,   23,

       34,   23,   23,   23,   23,   65,   65,   65,   23,   23,
       23,   23,   23,   67,   67,   67,   23,   23,   23,   23,
       23,   47,   39,   41,   41,   47,   41,   91,   91,   23,
       47,   23,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   26,   26,   26,
       42,   42,   42,  195,   42,   26,   26,   26,   26,   26,
       26,   26,   69,   69,   69,   26,   26,   26,   26,   26,

       26,   26,   32,  195,   32,   32,   32,   79,   79,   84,
      192,   84,   32,   32,   32,   32,   32,   32,   32,  134,
      134,   79,   32,   32,   32,   32,   32,   32,   32,   35,
       35,   35,   92,   92,  145,  145,   92,   35,   35,   35,
       35,   35,   35,   35,  126,  126,  126,   35,   35,   35,
       35,   35,   35,   35,   36,   36,   36,   59,   44,  191,
       44,   59,   36,   36,   36,  177,   59,   44,   48,   48,
      176,   45,   45,   36,   48,   36,   40,   45,   40,  174,
       40,   40,  164,   40,   45,  167,  167,   48,   58,   58,
       40,   44,   40,  135,   58,  135,   40,   43,   43,   43,

      163,   43,   43,   43,   43,  214,   96,   96,   43,   43,
       43,   43,   43,  106,  154,  106,   43,   43,   43,   43,
       43,   61,   61,  193,   75,   96,   76,   61,   75,   43,
      214,   43,   46,   75,   46,   76,   93,   93,  154,   76,
      182,  182,   93,  109,   76,  109,  106,  193,  162,   46,
       46,   46,  102,  102,  108,  108,  102,  155,  102,  155,
      108,  110,  110,  158,  110,   46,  211,  110,  112,  112,
      112,   46,   68,   68,   68,  153,  109,  209,  209,  112,
       68,   68,   68,  112,  156,  140,  138,  161,  112,  161,
      211,   68,   77,  155,   77,   77,   77,  136,  133,  115,

      115,  131,  124,   77,   77,  115,   77,   77,  156,  137,
      137,  137,  156,   77,   86,   86,   86,  122,  115,  137,
      161,  137,   86,   86,   86,  146,  146,  146,  168,  168,
      190,  121,  190,   86,  101,  217,  101,  217,  120,  168,
      146,  117,  190,  168,  178,  178,  178,  218,  168,  218,
      101,  101,  101,  101,  178,  111,  178,  217,  107,  101,
      101,  101,  101,  101,  101,  101,  189,  189,   95,  101,
      101,  101,  101,  101,  101,  101,  139,   94,  139,  139,
      139,  189,  194,  196,   88,   85,  139,  139,  139,  139,
      139,  139,  139,  216,   78,  216,  139,  139,  139,  139,

      139,  139,  139,  151,   70,  151,  194,  196,   64,  216,
      194,  212,  196,  212,  220,   63,  220,   62,   57,  151,
      151,  151,  151,  212,   56,   55,   54,   53,   52,   51,
       37,   27,   24,   21,   18,   17,   16,   15,   14,  151,
      152,   13,  152,   12,   11,   10,    9,  212,    8,    7,
        6,    5,  152,    0,    0,    0,  152,  152,  152,  152,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  152,  180,    0,  180,
      180,  180,    0,    0,    0,    0,    0,  180,  180,  180,
        0,  180,  180,    0,    0,    0,    0,    0,  180,  215,

        0,  215,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  215,    0,    0,  215,  215,  215,  215,  215,  215,
      215,    0,    0,    0,  215,  215,  215,  215,  215,  215,
      215,  219,    0,  219,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  219,    0,    0,  219,  219,  219,  219,
      219,  219,  219,    0,    0,    0,  219,  219,  219,  219,
      219,  219,  219,  222,  222,  222,  222,  222,  222,  223,
      223,  223,  223,  223,  223,  224,  224,  224,  224,  224,

      224,  225,  225,  225,    0,  225,  226,  226,    0,  226,
      226,  226,  227,  227,    0,  227,  227,  227,  228,  228,
        0,  228,  228,  228,  229,  229,    0,  229,  229,  229,
      230,    0,    0,  230,  230,  231,  231,  232,  232,  232,
      232,  232,  232,  233,  233,    0,  233,  233,  233,  234,
      234,  234,  234,  234,  234,  235,  235,    0,  235,  235,
      235,  236,  236,    0,  236,  236,  236,  237,  237,  237,
      237,  237,  237,  238,  238,  238,  238,  238,  238,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,

      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221
    } ;

#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yyg->yy_full_match; /* restore poss. backed-over text */ \
yyg->yy_lp = yyg->yy_full_lp; /* restore orig. accepting pos. */ \
yyg->yy_state_ptr = yyg->yy_full_state; /* restore orig. state */ \
yy_current_state = *yyg->yy_state_ptr; /* restore curr. state */ \
++yyg->yy_lp; \
goto find_rule; \
}

#define yymore() (yyg->yy_more_flag = 1)
#define YY_MORE_ADJ yyg->yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "tokenizer.l"
#line 2 "tokenizer.l"

#include "ruby.h"

// Anything longer is unlikely to be useful.
#define MAX_TOKEN_LEN 16

#define FEED2(s, l) do { \
    const char* __s = (s); \
    const size_t __l = (l); \
    const size_t __cl = __l > MAX_TOKEN_LEN? MAX_TOKEN_LEN : __l; \
    *yyextra = rb_str_new(__s, __cl); \
  } while(0)

#define FEED1(s) FEED2(s, strlen(s))

#define FEED() FEED2(yytext, yyleng)

#define FEED_STATIC(s) FEED2(s, sizeof(s) - 1)

#define FEED_SHEBANG(s) do { \
    const size_t __l = strlen(s); \
    const size_t __cl = __l > MAX_TOKEN_LEN? MAX_TOKEN_LEN : __l; \
    *yyextra = rb_str_new("SHEBANG#!", sizeof("SHEBANG#!") - 1); \
    rb_str_cat(*yyextra, s, __cl); \
  } while(0)

#define eat_until_eol() do { \
    int c; \
    while ((c = input(yyscanner)) != '\n' && c != EOF && c); \
    if (c == EOF || !c) \
      return 0; \
  } while (0)

#define eat_until_unescaped(q) do { \
    int c; \
    while ((c = input(yyscanner)) != EOF && c) { \
      if (c == '\n') \
        break; \
      if (c == '\\') { \
        c = input(yyscanner); \
        if (c == EOF || !c) \
          return 0; \
      } else if (c == q) \
        break; \
    } \
    if (c == EOF || !c) \
      return 0; \
  } while (0)

#line 981 "lex.linguist_yy.c"

#line 983 "lex.linguist_yy.c"

#define INITIAL 0
#define sgml 1
#define c_comment 2
#define xml_comment 3
#define haskell_comment 4
#define ocaml_comment 5
#define python_dcomment 6
#define python_scomment 7
#define roff_comment 8
#define punct 9

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE VALUE*

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    yy_state_type *yy_state_buf;
    yy_state_type *yy_state_ptr;
    char *yy_full_match;
    int yy_lp;

    /* These are only needed for trailing context rules,
     * but there's no conditional variable for that yet. */
    int yy_looking_for_trail_begin;
    int yy_full_lp;
    int *yy_full_state;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! yyg->yy_state_buf )
            yyg->yy_state_buf = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  , yyscanner);
            if ( ! yyg->yy_state_buf )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 58 "tokenizer.l"


#line 1271 "lex.linguist_yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yyg->yy_more_len = 0;
		if ( yyg->yy_more_flag )
			{
			yyg->yy_more_len = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			yyg->yy_more_flag = 0;
			}
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
		yy_current_state += YY_AT_BOL();

		yyg->yy_state_ptr = yyg->yy_state_buf;
		*yyg->yy_state_ptr++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 222 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*yyg->yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_current_state != 221 );

yy_find_action:
		yy_current_state = *--yyg->yy_state_ptr;
		yyg->yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yyg->yy_lp && yyg->yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yyg->yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yyg->yy_looking_for_trail_begin )
					{
					if ( yy_act == yyg->yy_looking_for_trail_begin )
						{
						yyg->yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yyg->yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yyg->yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					yyg->yy_full_match = yy_cp;
					yyg->yy_full_state = yyg->yy_state_ptr;
					yyg->yy_full_lp = yyg->yy_lp;
					break;
					}
				++yyg->yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yyg->yy_state_ptr;
			yyg->yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 60 "tokenizer.l"
{
  const char *off = strrchr(yytext, ' ');
  if (!off)
    off = yytext;
  else
    ++off;
  FEED_SHEBANG(off);
  eat_until_eol();
  return 1;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 71 "tokenizer.l"
{
  const char *off = strrchr(yytext, '/');
  if (!off)
    off = yytext;
  else
   ++off;
  if (strcmp(off, "env") == 0) {
    eat_until_eol();
  } else {
    FEED_SHEBANG(off);
    eat_until_eol();
    return 1;
  }
}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 86 "tokenizer.l"
{ FEED_STATIC("COMMENT#"); return 1; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 87 "tokenizer.l"
{ FEED_STATIC("COMMENT//!"); return 1; }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 88 "tokenizer.l"
{ FEED_STATIC("COMMENT//"); return 1; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 89 "tokenizer.l"
{ FEED_STATIC("COMMENT--"); return 1; }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 90 "tokenizer.l"
{ FEED_STATIC("COMMENT%"); return 1; }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 91 "tokenizer.l"
{ FEED_STATIC("COMMENT\""); return 1; }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 92 "tokenizer.l"
{ FEED_STATIC("COMMENT;"); return 1; }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 93 "tokenizer.l"
{ FEED_STATIC("COMMENT.\\\""); return 1; }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 94 "tokenizer.l"
{ FEED_STATIC("COMMENT'\\\""); return 1; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 96 "tokenizer.l"
{ FEED_STATIC("COMMENT/*"); return 1; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 97 "tokenizer.l"
{ FEED_STATIC("COMMENT/**"); BEGIN(c_comment); return 1; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 98 "tokenizer.l"
{ FEED_STATIC("COMMENT/*!"); BEGIN(c_comment); return 1; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 99 "tokenizer.l"
{ FEED_STATIC("COMMENT/*"); BEGIN(c_comment); return 1; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 100 "tokenizer.l"
{ FEED_STATIC("COMMENT<!--"); BEGIN(xml_comment); return 1; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 101 "tokenizer.l"
{ FEED_STATIC("COMMENT{-"); BEGIN(haskell_comment); return 1; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 102 "tokenizer.l"
{ FEED_STATIC("COMMENT(*"); BEGIN(ocaml_comment); return 1; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 103 "tokenizer.l"
{ FEED_STATIC("COMMENT\"\"\""); BEGIN(python_dcomment); return 1; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 104 "tokenizer.l"
{ FEED_STATIC("COMMENT'''"); BEGIN(python_scomment); return 1; }
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 105 "tokenizer.l"
{ FEED_STATIC("COMMENT.ig"); BEGIN(roff_comment); return 1; }
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 107 "tokenizer.l"
{ /* nothing */ }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 108 "tokenizer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 109 "tokenizer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 110 "tokenizer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 111 "tokenizer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 112 "tokenizer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 113 "tokenizer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 114 "tokenizer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 116 "tokenizer.l"
{ /* nothing */ }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 117 "tokenizer.l"
{ eat_until_unescaped('"'); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 118 "tokenizer.l"
{ eat_until_unescaped('\''); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 120 "tokenizer.l"
{ FEED_STATIC("LIT$INTDEC"); return 1; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 121 "tokenizer.l"
{ FEED_STATIC("LIT#INTDEC"); return 1; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 122 "tokenizer.l"
{ FEED_STATIC("LIT$INTHEX"); return 1; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 123 "tokenizer.l"
{ FEED_STATIC("LIT0xINTHEX"); return 1; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 124 "tokenizer.l"
{ FEED_STATIC("LITINTHEXh"); return 1; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 125 "tokenizer.l"
{ FEED_STATIC("LITINTOCT"); return 1; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 126 "tokenizer.l"
{ FEED_STATIC("LITINTDEC"); return 1; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 127 "tokenizer.l"
{ FEED_STATIC("LITNUM#"); return 1; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 129 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 130 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 131 "tokenizer.l"
{ FEED(); return 1; }
	YY_BREAK
case 44:
/* rule 44 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 133 "tokenizer.l"
{ FEED(); BEGIN(INITIAL); return 1; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 134 "tokenizer.l"
{ FEED(); BEGIN(INITIAL); return 1; }
	YY_BREAK
case 46:
/* rule 46 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 135 "tokenizer.l"
{ FEED(); BEGIN(INITIAL); return 1; }
	YY_BREAK
case 47:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 136 "tokenizer.l"
{ FEED(); BEGIN(INITIAL); return 1; }
	YY_BREAK
case 48:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 137 "tokenizer.l"
{ FEED(); BEGIN(INITIAL); return 1; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 138 "tokenizer.l"
{ yymore(); BEGIN(punct); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 139 "tokenizer.l"
{ yymore(); BEGIN(punct); }
	YY_BREAK
case YY_STATE_EOF(punct):
#line 140 "tokenizer.l"
{ FEED2(yytext, yyleng - 1); BEGIN(INITIAL); return 1; }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 142 "tokenizer.l"
{ /* nothing */ }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 144 "tokenizer.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1674 "lex.linguist_yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(sgml):
			case YY_STATE_EOF(c_comment):
			case YY_STATE_EOF(xml_comment):
			case YY_STATE_EOF(haskell_comment):
			case YY_STATE_EOF(ocaml_comment):
			case YY_STATE_EOF(python_dcomment):
			case YY_STATE_EOF(python_scomment):
			case YY_STATE_EOF(roff_comment):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;
	yy_current_state += YY_AT_BOL();

	yyg->yy_state_ptr = yyg->yy_state_buf;
	*yyg->yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 222 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*yyg->yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */

	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 222 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 221);
	if ( ! yy_is_jam )
		*yyg->yy_state_ptr++ = yy_current_state;

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

    yyg->yy_state_buf = 0;
    yyg->yy_state_ptr = 0;
    yyg->yy_full_match = 0;
    yyg->yy_lp = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    yyfree ( yyg->yy_state_buf , yyscanner);
    yyg->yy_state_buf  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 144 "tokenizer.l"



